# Generated by Django 3.1.7 on 2021-03-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_garbage_collector',
            field=models.BooleanField(default=False),
        ),
    ]
