# Generated by Django 3.1.7 on 2021-03-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usermodel_is_garbage_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='show_rating',
            field=models.BooleanField(default=True),
        ),
    ]
