# Generated by Django 3.1.7 on 2021-04-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210317_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_commercial',
            field=models.BooleanField(default=False),
        ),
    ]
