# Generated by Django 3.1.7 on 2021-04-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usermodel_is_commercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='show_rating',
        ),
    ]
