# Generated by Django 3.1.7 on 2021-04-03 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=350)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbage_type', models.CharField(choices=[('OR', 'Organic'), ('GL', 'Glass'), ('ME', 'Metal'), ('PA', 'Paper'), ('PL', 'Plastic')], default='OR', max_length=2)),
                ('points', models.IntegerField(default=0)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbage_type', models.CharField(choices=[('OR', 'Organic'), ('GL', 'Glass'), ('ME', 'Metal'), ('PA', 'Paper'), ('PL', 'Plastic')], default='OR', max_length=2)),
                ('service_name', models.CharField(max_length=150)),
                ('price_per_kg', models.FloatField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.location')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('garbage_type', models.CharField(choices=[('OR', 'Organic'), ('GL', 'Glass'), ('ME', 'Metal'), ('PA', 'Paper'), ('PL', 'Plastic')], default='OR', max_length=2)),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('A', 'In Progress'), ('D', 'Done')], default='Q', max_length=1)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
