# Generated by Django 3.1.7 on 2021-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0002_transaction_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mass',
            field=models.FloatField(default=0.0),
        ),
    ]
